### ISSUE TITLE
puppet-agent-6 upgrade fails

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/homebrew-puppet#137]
## Describe the Bug
Puppet Agent 6 Upgrade throws an error:

```
brew cask upgrade puppetlabs/puppet/puppet-agent-6
==> Upgrading 1 outdated package:
puppetlabs/puppet/puppet-agent-6 6.10.1 -> 6.11.1
==> Upgrading puppet-agent-6
==> Downloading https://downloads.puppet.com/mac/puppet6/10.14/x86_64/puppet-agent-6.11.1-1.osx10.14.dmg
Already downloaded: /Users/simonhoenscheid/Library/Caches/Homebrew/downloads/0f0bf176ec65ed2e3217f125117ffd87f68c675e7483cf3b841b9ec2f6d83c3a--puppet-agent-6.11.1-1.osx10.14.dmg
==> Verifying SHA-256 checksum for Cask 'puppet-agent-6'.
==> Removing launchctl service puppet
rm: puppet: is a directory
==> Purging files for version 6.11.1 of Cask puppet-agent-6
Error: Failure while executing; `/bin/rm -f -- puppet` exited with 1. Here's the output:
rm: puppet: is a directory

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:109:in `block (2 levels) in uninstall_launchctl'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:86:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:86:in `block in uninstall_launchctl'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:84:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:84:in `uninstall_launchctl'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:68:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:11:in `block in uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:10:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:454:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:450:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:411:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:94:in `upgrade_cask'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:48:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```
## Expected Behavior
the upgrade works

## Environment

Systemversion:	macOS 10.15.1 (19B88)
Kernel-Version:	Darwin 19.0.0

**Comment by MikaelSmith** [comment]
This looks like it may have been failing to remove some of the plist files because the name was wrong, but it's also surprising it's finding a directory to remove. Do you have a local directory called `puppet` where you ran `brew cask upgrade`?

I think the fix for this is to update https://github.com/puppetlabs/homebrew-puppet/blob/master/templates/puppet-agent-6.rb.erb#L7-L8 to `com.puppetlabs.puppet` and `com.puppetlabs.pxp-agent` and regenerate the casks. Similar treatment needed for the other templates.

**Comment by MikaelSmith** [comment]
Actually, what was there before correctly uninstalls the service because those are the names they go by. I think Homebrew is doing some extra work that causes an issue in your environment. It shouldn't be trying to delete a file in your working directory. https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/abstract_uninstall.rb#L105-L109 in particular seems suspect.

I'd recommend filing an issue with the Homebrew project.

**Comment by MikaelSmith** [comment]
Closing as I believe the cask is correctly formed and this is instead running into odd behavior with Homebrew.
