### ISSUE TITLE
Installing pdk fails with permission errors in /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/

### ISSUE THREAD

**Issue by damonmaria** [puppetlabs/homebrew-puppet#181]
## Describe the Bug
```shell
$ brew doctor
Your system is ready to brew.
$ brew cask install puppetlabs/puppet/pdk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
horos

==> Caveats

    PDK binaries are installed in /opt/puppetlabs/pdk/bin, which is sourced by an /etc/paths.d entry.
    /opt/puppetlabs/pdk/bin may not be included in your current $PATH but should be included in new shells.

==> Downloading https://downloads.puppet.com/mac/puppet/10.15/x86_64/pdk-1.17.0.0-1.osx10.15.dmg
Already downloaded: /Users/damon/Library/Caches/Homebrew/downloads/38ef982fd088d2c1f2ed98425f1f2871bc01d87c9dc3a35df56e5a2208a47e70--pdk-1.17.0.0-1.osx10.15.dmg
==> Verifying SHA-256 checksum for Cask 'pdk'.
==> Installing Cask pdk
==> Running installer for pdk; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is pdk
installer: Upgrading at base path /
installer: The upgrade was successful.
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/bundler: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/bundler: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/bundler: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2: Operation not permitted
==> Purging files for version 1.17.0.0 of Cask pdk
Error: Failure while executing; `/bin/chmod -R -- a\+rX /opt/puppetlabs/pdk` exited with 1. Here's the output:
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/bundler: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/bundler: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/bundler: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/gems/2.4.0/gems/bundler-1.17.2: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/rubygems: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/site_ruby/2.5.0/bundler: Operation not permitted
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2: Operation not permitted
chmod: /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2: Permission denied
chmod: Unable to change file mode on /opt/puppetlabs/pdk/private/ruby/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-1.17.2: Operation not permitted

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/staged.rb:11:in `set_permissions'
/usr/local/Homebrew/Library/Taps/puppetlabs/homebrew-puppet/Casks/pdk.rb:42:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:24:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

## Expected Behavior
Should install PDK as it used to on my system. 

## Steps to Reproduce
1. `brew cask install puppetlabs/puppet/pdk`

## Environment
 - Version: 1.17.0.0-1
 - Platform:  MacOS 10.15.3

## Additional Context
I've installed and upgrade pdk using brew through many versions. Have uninstalled and reinstalled several attempts over the last month with always this same result.

**Comment by MikaelSmith** [comment]
Can someone from @puppetlabs/pdk take a look?

**Comment by scotje** [comment]
Hello @damonmaria, can you try the following sequence and see if that resolves things? We had a broken build a couple releases back and unfortunately it sometimes takes a full uninstall and purge to get things fixed up:

```
brew cask uninstall pdk
sudo rm -rf /opt/puppetlabs/pdk
brew cask install puppetlabs/puppet/pdk
```

**Comment by damonmaria** [comment]
@scotje Thanks so much. That worked. And I was just about to have to modify one of our PDK modules :)

I had previously performed the uninstall and that was not enough. Just assumed the uninstall would have deleted the directory.

**Comment by scotje** [comment]
Great! Sorry for the inconvenience!
