### ISSUE TITLE
during PDK upgrade, uninstall process fails

### ISSUE THREAD

**Issue by jonathanc-blinds** [puppetlabs/homebrew-puppet#37]
when upgrading to the newest PDK cask, I receive the following output:
```
$ brew cask upgrade pdk
==> Upgrading 1 outdated package:
puppetlabs/puppet/pdk  -> 1.7.1.0
==> Satisfying dependencies
==> Downloading https://downloads.puppet.com/mac/puppet5/10.13/x86_64/pdk-1.7.1.0-1.osx10.13.dmg
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/3e4c1bb1cf2c12c4b1bdcec9dc89277ef5743945ce6533a7e6f9e12ef7450155--pdk-1.7.1.0-1.osx10.13.dmg
==> Verifying SHA-256 checksum for Cask 'pdk'.
==> Starting upgrade for Cask pdk
==> Running uninstall process for pdk; your password may be necessary
==> Uninstalling packages:
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/pdk/unknown, /usr/local/Caskroom/pdk/unknown.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:389:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:76:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```
I'm upgrading from 1.7.0.0 on MacOS 10.14.1 (Mojave)

**Comment by MikaelSmith** [comment]
I'm not really sure what happened there other than it seems Homebrew Cask didn't know what version of pdk was already installed. Maybe worth following the homebrew-cask link for reporting a bug?

**Comment by jonathanc-blinds** [comment]
I've opened a github issue for homebrew here: https://github.com/Homebrew/homebrew-cask/issues/54714
